// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurgiTech.Data;

#nullable disable

namespace SurgiTech.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921160858_AddShopSettings")]
    partial class AddShopSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurgiTech.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("SurgiTech.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 9821,
                            HospitalName = "City Hospital Care",
                            OrderDate = new DateTime(2026, 9, 20, 21, 8, 50, 304, DateTimeKind.Local).AddTicks(8606),
                            Status = "Shipped",
                            TotalAmount = 14250.00m
                        },
                        new
                        {
                            Id = 9822,
                            HospitalName = "St. Jude Clinic",
                            OrderDate = new DateTime(2026, 9, 21, 21, 8, 50, 304, DateTimeKind.Local).AddTicks(9498),
                            Status = "Processing",
                            TotalAmount = 8900.00m
                        });
                });

            modelBuilder.Entity("SurgiTech.Models.ShopSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings");
                });

            modelBuilder.Entity("SurgiTech.Models.SurgicalInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialGrade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Scalpels",
                            ImageUrl = "/images/default-instrument.jpg",
                            MaterialGrade = "Grade-A Stainless Steel",
                            Name = "Scalpels & Blades",
                            StockQuantity = 12400,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Forceps",
                            ImageUrl = "/images/default-instrument.jpg",
                            MaterialGrade = "Titanium Coated",
                            Name = "Hemostatic Forceps",
                            StockQuantity = 8150,
                            UnitPrice = 45.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Scissors",
                            ImageUrl = "/images/default-instrument.jpg",
                            MaterialGrade = "Surgical Grade",
                            Name = "Retractors & Scissors",
                            StockQuantity = 5200,
                            UnitPrice = 30.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
